// src/icons/index.ts
import {
  Bars3Icon as MenuIcon,
  BellIcon,
  MoonIcon,
  SunIcon,
  MagnifyingGlassIcon as SearchIcon,
  UserIcon as OutlinePersonIcon,
  Cog6ToothIcon as OutlineCogIcon,
  ArrowRightOnRectangleIcon as OutlineLogoutIcon,
  HomeIcon,
  ChartBarIcon,
  UsersIcon,
  CreditCardIcon as MoneyIcon,
  ShoppingCartIcon as CartIcon,
  ChatBubbleLeftRightIcon as ChatIcon,
  EnvelopeIcon as MailIcon,
  TrashIcon,
  PencilIcon as EditIcon,
  HeartIcon,
} from '@heroicons/react/24/solid'

export {
  MenuIcon,
  BellIcon,
  MoonIcon,
  SunIcon,
  SearchIcon,
  OutlinePersonIcon,
  OutlineCogIcon,
  OutlineLogoutIcon,
  HomeIcon,
  ChartBarIcon,
  UsersIcon,
  MoneyIcon,
  CartIcon,
  ChatIcon,
  MailIcon,
  TrashIcon,
  EditIcon,
  HeartIcon,
}
