name: Commitlint

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Skip merge commits
        run: |
          if git log -1 --pretty=%s | grep -q "^Merge"; then
            echo "Merge commit detected. Skipping commitlint..."
            exit 0
          fi

      - name: Run commitlint
        uses: opensource-nepal/commitlint@v1
