name: Commitlint

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest commit message
        id: commit
        run: echo "message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT

      - name: Run commitlint
        if: ${{ !startsWith(steps.commit.outputs.message, 'Merge') }}
        uses: opensource-nepal/commitlint@v1
